### Health check

GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks HTTP/1.1

### GET task by ID
GET http://localhost:3000/v1/tasks/1 HTTP/1.1

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1

### GET project by ID
GET http://localhost:3000/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1